### ISSUE TITLE
Generic error message / SSH URL format

### ISSUE THREAD

**Issue by macbookandrew** [axllent/gitlabci-composer-update-mr#1]
This looks like a great tool and I’d love to use it. Unfortunately, I’ve only been able to get this rather generic error message:

```
==========
Error creating merge request: exit status 128
==========
```

It appears to be coming from [this section of code](https://github.com/axllent/gitlabci-composer-update-mr/blob/d5864f788aa28724cb166dc1f0b38900474c5167/app/git.go#L30-L48), but I’m not clear which one specifically or what the error is.

I am using a self-hosted GitLab instance, but I don’t think that’s causing the issue.

I’m not at all familiar with Go; is there any way to add a more specific error message for each of those conditions to try and track down the root cause?

**Comment by axllent** [comment]
Thanks for the feedback @macbookandrew . Whilst I'm unsure as to why you are getting an error, I have just pushed a change that should print out the error message when there is an error, which hopefully helps us find out what is going wrong.

I use this utility on two separate self-hosted Gitlab instances, so that is not the issue. I suspect it may be some permission issues on the Gitlab repository itself with regards to who can push a merge request, but I'm not sure.

Please try again (I've updated the docker images) and let me know if this now returns a more useful error? Thanks.

**Comment by macbookandrew** [comment]
Thanks a lot! That gave me this. We have disabled Git access over HTTP because we require 2FA. I’ll add a step to convert URL structure to work around this.

```
remote: Git access over HTTP is not allowed
fatal: unable to access 'https://path-to-my-project/': The requested URL returned error: 403
```

**Comment by macbookandrew** [comment]
Looks like the image needs SSH in order for that to work:

```
error: cannot run ssh: No such file or directory
```

**Comment by axllent** [comment]
Thanks for the updated merge request! I've just rebuild & pushed the docker images with the openssh-client installed - please test and let me know if this solves your issue?

**Comment by macbookandrew** [comment]
Getting closer. Now it’s using `root` as the git username instead of `git`:

```
$ gitlabci-composer-update-mr <name> <email> <branch>
Pulling latest changes from <branch>
Warning: Permanently added the RSA host key for IP address <IP address> to the list of known hosts.
root@my-gitlab-server: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
==========
Error switching branch: exit status 1
==========
```

Looking at your codebase, I see some [other code](https://github.com/axllent/gitlabci-composer-update-mr/blob/0c214d1d84c754f485ddb0480de094ce9f0837eb/app/git.go#L85-L104) that may not be compatible with our SSH-only server. I may end up having to fork and rework it for SSH.

**Comment by axllent** [comment]
Ahh yes, that makes perfect sense (good find!). Much of that I inherited (rewrote into Go) based on the original PHP module, so I'm sure that logic can be reworked/improved. Those git environment variables are based on `CI_REPOSITORY_URL` environment setting passed through from the CI process, however I don't know if that can be easily converted into an SSH-type URL. 

If I was to add a "debug line" to that function to print out your `CI_REPOSITORY_URL` and you could tell me what it says (you should of course substitute your actual data with fake) then that would be a great starting point for me. Please tell me which image you're using and I'll update it for the test.

**Comment by macbookandrew** [comment]
We’ve run into this on other pipelines and have this set up to convert the URL structure:

```shell
$ SSH_GIT_URL=$(echo "$CI_REPOSITORY_URL" | sed 's/git.my-gitlab-server\//git.my-gitlab-server:/' | cut -d "@" -f 2)
$ git remote set-url origin $SSH_GIT_URL
$ git remote get-url origin # verify URL
git.my-gitlab-server:demo/test-project.git
$ gitlabci-composer-update-mr <name> <email> <branch>
```

So far so good, and we also have the SSH key added in with a `before_script` step. But apparently the current user in the container is `root`, not `git`, so the `git checkout` command fails due to invalid username.

**Comment by axllent** [comment]
I see, however I don't know the format of `CI_REPOSITORY_URL` is when HTTP(S) access is specifically disabled. If that format is different to the standard HTTP(s) syntax then we can set up git differently in that case. I would however assume that a gitlab-ci-token is supplied one way or another (maybe via the `CI_JOB_TOKEN` variable?).

One thing that confuses me a little is a previous comment you made that you "have disabled Git access over HTTP because we require 2FA". We have 2FA as well and allow HTTPS (the "gitlab-ci-token" bypasses 2FA, like an "app password" in Google etc). I don't see why HTTPS is disabled because of 2FA? Regardless though, it would be nice to not _have to_ use HTTP(S), but I'm unsure what I can do to fix that from my end. as I don't have a similar environment here to test with.

**Comment by macbookandrew** [comment]
Yes, there is a gitlab-ci-token supplied; here’s the `CI_REPOSITORY_URL` format:

```
https://gitlab-ci-token:[MASKED]@git.my-gitlab-server/test-project.git
```

Our GitLab administrator has disabled HTTP(S) access as described [here](https://docs.gitlab.com/ee/user/admin_area/settings/visibility_and_access_controls.html#configure-enabled-git-access-protocols) and is enforcing 2FA for all user accounts. I _think_ 2FA breaks `git clone|pull|push https://my-gitlab-server` but I could be wrong. l’ll see if they can enable HTTPS for `git` operations and see if that helps.

**Comment by macbookandrew** [comment]
We re-enabled HTTP(S) access and this worked flawlessly.

It seems like it would be a major undertaking to make this work for both HTTPS and SSH formats and probably not worth the effort.

Would you like me to submit a PR to remove the `openssh-client` from the Docker image?

Thanks for your help!

**Comment by axllent** [comment]
Glad to hear it is working! Don't worry about the PR, I have reverted your change and am building new images now.
